# Generated by Django 2.0.2 on 2018-03-05 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30, unique=True)),
                ('weight', models.IntegerField()),
                ('parent_set', models.ManyToManyField(related_name='_category_parent_set_+', to='capstoneproject.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhraseSpelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling', models.CharField(max_length=100, unique=True)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstoneproject.Phrase')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strong', models.BooleanField()),
                ('weight', models.SmallIntegerField(choices=[(0, 'innocuous'), (1, 'slight'), (2, 'moderate'), (3, 'heavy')])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstoneproject.Category')),
            ],
        ),
        migrations.CreateModel(
            name='WordSpelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling', models.CharField(max_length=30, unique=True)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstoneproject.Word')),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='word_category_set',
            field=models.ManyToManyField(to='capstoneproject.WordCategory'),
        ),
        migrations.AddField(
            model_name='phrase',
            name='word_category_set',
            field=models.ManyToManyField(to='capstoneproject.WordCategory'),
        ),
        migrations.AddField(
            model_name='phrase',
            name='word_set',
            field=models.ManyToManyField(to='capstoneproject.Word'),
        ),
    ]
