# Generated by Django 2.0.2 on 2018-02-18 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneproject', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category']},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['word', 'category_id']},
        ),
    ]
