# Generated by Django 2.0.2 on 2018-02-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='phrase',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='phrasespelling',
            name='spelling',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='wordspelling',
            name='spelling',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
