# Generated by Django 2.0.3 on 2018-03-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word_features',
            field=models.ManyToManyField(related_name='words', to='capstoneproject.WordFeature'),
        ),
    ]
