# Generated by Django 2.0.2 on 2018-02-20 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneproject', '0002_auto_20180220_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhraseSpelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling', models.CharField(max_length=100)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstoneproject.Phrase')),
            ],
        ),
        migrations.RenameModel(
            old_name='Spelling',
            new_name='WordSpelling',
        ),
        migrations.RenameField(
            model_name='wordspelling',
            old_name='word_or_phrase',
            new_name='word',
        ),
    ]
