# Generated by Django 2.0.2 on 2018-02-19 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneproject', '0002_auto_20180217_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Spelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='word',
            options={},
        ),
        migrations.AddField(
            model_name='spelling',
            name='word_or_phrase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstoneproject.Word'),
        ),
        migrations.AddField(
            model_name='phrase',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstoneproject.Category'),
        ),
        migrations.AddField(
            model_name='phrase',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capstoneproject.Word'),
        ),
    ]
