# Generated by Django 2.0.3 on 2018-04-05 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneproject', '0003_auto_20180404_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='categoryrating',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='category_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userstorage',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_storage', to='capstoneproject.Category'),
        ),
        migrations.AlterField(
            model_name='userstorage',
            name='ratings',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_storage', to='capstoneproject.Rating'),
        ),
        migrations.AlterField(
            model_name='userstorage',
            name='word_features',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_storage', to='capstoneproject.WordFeature'),
        ),
        migrations.AlterField(
            model_name='word',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='words', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wordfeature',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='word_features', to=settings.AUTH_USER_MODEL),
        ),
    ]
