# Generated by Django 2.0.2 on 2018-02-24 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneproject', '0003_auto_20180224_0321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrase',
            old_name='word',
            new_name='word_set',
        ),
    ]
