
from capstoneproject.app_forms.change_password_form import ChangePasswordForm
from capstoneproject.app_forms.change_username_form import ChangeUsernameForm
from capstoneproject.app_forms.change_username_password_form import ChangeUsernamePasswordForm
from capstoneproject.app_forms.copy_in_form import CopyInForm
from capstoneproject.app_forms.login_form import LoginForm
from capstoneproject.app_forms.movie_search_form import MovieSearchForm
from capstoneproject.app_forms.signup_form import SignUpForm
from capstoneproject.app_forms.song_search_form import SongSearchForm
from capstoneproject.app_forms.tv_show_search_form import TVShowSearchForm
from capstoneproject.app_forms.upload_file_form import UploadFileForm
from capstoneproject.app_forms.webpage_search_form import WebsiteSearchForm
